<a href="https://colab.research.google.com/github/prakha10/data-visualization.github.io/blob/main/Quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Pandas For Data Analysis:Quiz II
  Pratim Khadka<br/>
  1/14/2022

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/prakha10/data-visualization.github.io/main/iris.csv',header = None)
head = ['SepalLength','SepalWidth','PedalLength','PedalWidth','Class'] 
#https://raw.githubusercontent.com/prakha10/data-visualization.github.io/main/iris.csv 
df.columns = head
df.head()

   SepalLength  SepalWidth  PedalLength  PedalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

#Geting the column names.

In [ ]:
df.columns

Index(['SepalLength', 'SepalWidth', 'PedalLength', 'PedalWidth', 'Class'], dtype='object')

#Calling a column and finding it's mean.

In [ ]:
df.SepalLength

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLength, Length: 150, dtype: float64

In [ ]:
df.SepalLength.mean()

5.843333333333335

#Finding the last row.

In [ ]:
df.iloc[149:]

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
149          5.9         3.0          5.1         1.8  Iris-virginica

#Melting the data keeping two columns of values and the type of flower.

In [ ]:
df_melt = df.melt(id_vars = 'Class',
                  value_vars = ['SepalLength','SepalWidth'],
                  var_name = ['colmuns'])
                  
df_melt.tail()

              Class     colmuns  value
295  Iris-virginica  SepalWidth    3.0
296  Iris-virginica  SepalWidth    2.5
297  Iris-virginica  SepalWidth    3.0
298  Iris-virginica  SepalWidth    3.4
299  Iris-virginica  SepalWidth    3.0

In [ ]:
df_melt.pivot(columns = 'colmuns', values = 'value')

colmuns  SepalLength  SepalWidth
0                5.1         NaN
1                4.9         NaN
2                4.7         NaN
3                4.6         NaN
4                5.0         NaN
..               ...         ...
295              NaN         3.0
296              NaN         2.5
297              NaN         3.0
298              NaN         3.4
299              NaN         3.0

[300 rows x 2 columns]

#Selecting flowers that have pedal length greater than 5 and sepal length less than 7.

In [ ]:
df.query('PedalLength >5 and SepalLength < 7').head()

     SepalLength  SepalWidth  PedalLength  PedalWidth            Class
83           6.0         2.7          5.1         1.6  Iris-versicolor
100          6.3         3.3          6.0         2.5   Iris-virginica
101          5.8         2.7          5.1         1.9   Iris-virginica
103          6.3         2.9          5.6         1.8   Iris-virginica
104          6.5         3.0          5.8         2.2   Iris-virginica

# Grouping the data by type of flower and compute mean and median.

In [ ]:
df.groupby(by = 'Class').agg(['mean','median'])

                SepalLength        SepalWidth  ... PedalLength PedalWidth
                       mean median       mean  ...      median       mean median
Class                                          ...
Iris-setosa           5.006    5.0      3.418  ...        1.50      0.244    0.2
Iris-versicolor       5.936    5.9      2.770  ...        4.35      1.326    1.3
Iris-virginica        6.588    6.5      2.974  ...        5.55      2.026    2.0

[3 rows x 8 columns]