<a href="https://colab.research.google.com/github/prakha10/data-visualization.github.io/blob/main/Untitled20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pa

df = pa.read_csv('https://raw.githubusercontent.com/prakha10/data-visualization.github.io/main/iris.csv')
head = ['SepalLength','SepalWidth','PedalLength','PedalWidth','Class'] 
df.columns = head
df.head().T

                       0            1            2            3            4
SepalLength          4.9          4.7          4.6          5.0          5.4
SepalWidth           3.0          3.2          3.1          3.6          3.9
PedalLength          1.4          1.3          1.5          1.4          1.7
PedalWidth           0.2          0.2          0.2          0.2          0.4
Class        Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

In [12]:
df.SepalLength.mean()

5.848322147651008

In [8]:
df.SepalLength.astype('int')

0      4
1      4
2      4
3      5
4      5
      ..
144    6
145    6
146    6
147    6
148    5
Name: SepalLength, Length: 149, dtype: int64

In [9]:
df.SepalLength.agg(['mean','median','count', 'std'])

mean        5.848322
median      5.800000
count     149.000000
std         0.828594
Name: SepalLength, dtype: float64

# Converting SepalLength to integer doesnt have any affect in the mean value.

#Gathering the mean, median, count and standard deviation of all columns when grouped by Class.

In [16]:
df.groupby('Class').SepalLength.agg(['mean','median','count', 'std'])

                     mean  median  count       std
Class
Iris-setosa      5.004082     5.0     49  0.355879
Iris-versicolor  5.936000     5.9     50  0.516171
Iris-virginica   6.588000     6.5     50  0.635880

In [17]:
df.groupby('Class').SepalWidth.agg(['mean','median','count', 'std'])

                     mean  median  count       std
Class
Iris-setosa      3.416327     3.4     49  0.384787
Iris-versicolor  2.770000     2.8     50  0.313798
Iris-virginica   2.974000     3.0     50  0.322497

In [19]:
df.groupby('Class').PedalLength.agg(['mean','median','count', 'std'])

                     mean  median  count       std
Class
Iris-setosa      1.465306    1.50     49  0.175061
Iris-versicolor  4.260000    4.35     50  0.469911
Iris-virginica   5.552000    5.55     50  0.551895

In [20]:
df.groupby('Class').PedalWidth.agg(['mean','median','count', 'std'])

                     mean  median  count       std
Class
Iris-setosa      0.244898     0.2     49  0.108130
Iris-versicolor  1.326000     1.3     50  0.197753
Iris-virginica   2.026000     2.0     50  0.274650