<a href="https://colab.research.google.com/github/prakha10/data-visualization.github.io/blob/main/Untitled9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

#Examine the average trip on Austin bike share grouping by property_type column from the bikeshare_stations table.

In [2]:
%%bigquery --project datavids

SELECT name, property_type
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
LIMIT 50

                                                 name property_type
0                                          Pease Park          None
1                                     Republic Square          None
2                                    Waller & 6th St.          None
3                     Bullock Museum @ Congress & MLK          None
4                     State Capitol @ 14th & Colorado          None
5                             ACC - Rio Grande & 12th          None
6                            ACC - West & 12th Street          None
7               Republic Square @ Guadalupe & 4th St.          None
8                                    5th & San Marcos          None
9                                   Rainey @ River St          None
10                            Toomey Rd @ South Lamar          None
11                         East 7th & Pleasant Valley          None
12                            OFFICE/Main/Shop/Repair          None
13                                 6th & Navasota St.          None
14                                    8th & Guadalupe          None
15                            Red River & LBJ Library          None
16               State Parking Garage @ Brazos & 18th          None
17                                   Zilker Park West          None
18                                       Lavaca & 6th          None
19                                       Nueces @ 3rd          None
20                         Barton Springs & Riverside
21                                     Boardwalk West      parkland
22                            Congress & Cesar Chavez      parkland
23                                Barton Springs Pool      parkland
24                               Riverside @ S. Lamar      parkland
25                                        Zilker Park      parkland
26                               Rainey St @ Cummings      parkland
27                                     13th & Trinity      sidewalk
28                              22nd 1/2 & Rio Grande      sidewalk
29                East 5th/Shady @ Eastside Bus Plaza      sidewalk
30                           South Congress & Academy      sidewalk
31                                     8th & Congress      sidewalk
32                                       Lavaca & 6th      sidewalk
33                  Capitol Station / Congress & 11th      sidewalk
34                                       8th & Lavaca      sidewalk
35                             South Congress & James      sidewalk
36                        Barton Springs @ Kinney Ave      sidewalk
37                               Trinity & 6th Street      sidewalk
38                                     6th & Congress      sidewalk
39                               21st & Speedway @PCL      sidewalk
40                   23rd & San Jacinto @ DKR Stadium      sidewalk
41                                 11th & San Jacinto      sidewalk
42                  Convention Center / 3rd & Trinity      sidewalk
43                             Red River & 8th Street      sidewalk
44                                     Plaza Saltillo      sidewalk
45                Long Center @ South 1st & Riverside      sidewalk
46  State Capitol Visitors Garage @ San Jacinto & ...      sidewalk
47                  Republic Square @ 5th & Guadalupe      sidewalk
48  South Congress & Barton Springs at the Austin ...      sidewalk
49                       Lake Austin Blvd @ Deep Eddy      sidewalk

In [6]:
%%bigquery --project datavids
WITH t as(
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE property_type)

SELECT *
FROM t as table1 JOIN t as table2 ON table1.property_type = table2.property_type

Executing query with job ID: 624e8174-bde6-4e7c-a8e3-09b234336652
Query executing: 0.26s

ERROR:
 400 Unrecognized name: property_type at [4:7]

(job ID: 624e8174-bde6-4e7c-a8e3-09b234336652)

                           -----Query Job SQL Follows-----

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:WITH t as(
   2:SELECT *
   3:FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
   4:WHERE property_type)
   5:
   6:SELECT *
   7:FROM t as table1 JOIN t as table2 ON table1.property_type = table2.property_type
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |

#Is average time on trips starting from 'parkland' longer than from 'sidewalks'?
 # lets look at the process .

In [5]:
%%bigquery --project datavids
WITH t as(
SELECT *
FROM  `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE property_type= parkland)

SELECT table1.start_station_name, SUM(CASE WHEN table1.parkland < table2.sidewalk Then 1 ELSE 0 END) as average_time_longer 
FROM t as table1 JOIN t as table2 ON table1.property_type = table2.property_type
GROUP BY table1.start_station_name

Executing query with job ID: 8f2e7e3d-4e17-4ba8-ab79-78c1f96f7a50
Query executing: 0.31s

ERROR:
 400 Unrecognized name: property_type at [4:7]

(job ID: 8f2e7e3d-4e17-4ba8-ab79-78c1f96f7a50)

                                                 -----Query Job SQL Follows-----

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:WITH t as(
   2:SELECT *
   3:FROM  `bigquery-public-data.austin_bikeshare.bikeshare_trips`
   4:WHERE property_type= parkland)
   5:
   6:SELECT table1.start_station_name, SUM(CASE WHEN table1.parkland < table2.sidewalk Then 1 ELSE 0 END) as average_time_longer
   7:FROM t as table1 JOIN t as table2 ON table1.property_type = table2.property_type
   8:GROUP BY table1.start_station_name
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |